'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null,bid=localStorage.getItem('fm-bid'),sid=null,pid=null,rid=null,tab='scans',dirty=false,drag=null,lastJob='',uploading=false;
const drafts={};
const batch=()=>state?.batches.find(b=>b.id===bid), region=()=>batch()?.regions.find(r=>r.id===rid), pair=()=>batch()?.pairs.find(p=>p.id===pid);
async function api(path,data,method='POST'){
  const options={method,headers:{'X-App-Token':window.APP_TOKEN}};
  if(data instanceof FormData)options.body=data;else if(data!==undefined){options.headers['Content-Type']='application/json';options.body=JSON.stringify(data);}
  const response=await fetch(path,options);const result=await response.json();if(!response.ok)throw Error(result.error||'İşlem tamamlanamadı.');return result;
}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),6500);}
async function act(fn){try{await fn();}catch(e){toast(e.message);console.error(e);}}
async function refresh(renderNow=true){state=await api('/api/state',undefined,'GET');if(!batch())bid=state.batches[0]?.id||null;localStorage.setItem('fm-bid',bid||'');if(renderNow)render();updateJob();}
function updateJob(){const j=state.job;$('#jobbar').hidden=!['running','error','done','cancelled'].includes(j.status);$('#jobbar').classList.toggle('error',j.status==='error');$('#jobtext').textContent=j.message;$('#cancelJob').hidden=j.status!=='running';$('.spinner').hidden=j.status!=='running';}
function preview(p){return `/api/batches/${bid}/pair/${encodeURIComponent(p.id)}/preview?v=${batch().revision}`;}
function scanURL(s){return `/api/batches/${bid}/scan/${s.id}`;}
function pendingScans(){const b=batch();return b?b.scans.filter(s=>!b.regions.some(r=>r.scan_id===s.id)).length:0;}
function approved(){return batch()?.pairs.filter(p=>!p.needs_review)||[];}
function busy(){return state?.job.status==='running';}
function isLocal(){return (state?.settings?.backend||'local')==='local';}
function renderSettings(){
 const c=state.settings,router=c.backend==='openrouter',models=router?state.openrouter.models:state.models,mkey=router?'api_model':'model',ekey=router?'api_effort':'effort';
 const selected=models.find(m=>m.id===c[mkey])||{id:'',name:'Model seç',efforts:[router?'default':'medium']};
 $('#processingSettings').innerHTML=`<label>İşleme<select id="backendSelect" ${busy()?'disabled':''}><option value="local" ${isLocal()?'selected':''}>Yerel · Yapay zekâsız</option><option value="ai" ${c.backend==='ai'?'selected':''}>Yapay zekâ · Codex</option><option value="openrouter" ${router?'selected':''}>API · OpenRouter</option></select></label><label>Model<select id="modelSelect" ${busy()||isLocal()?'disabled':''}>${router?'<option value="">Model seç</option>':''}${models.map(m=>`<option value="${esc(m.id)}" ${m.id===c[mkey]?'selected':''}>${esc(m.name)}</option>`).join('')}</select></label><label>Effort<select id="effortSelect" ${busy()||isLocal()?'disabled':''}>${selected.efforts.map(e=>`<option value="${esc(e)}" ${e===c[ekey]?'selected':''}>${e==='default'?'Model varsayılanı':esc(e)}</option>`).join('')}</select></label>${isLocal()?`<label>Tarama yerleşimi<select id="layoutSelect" ${busy()?'disabled':''}>${Object.entries(state.layouts).map(([v,t])=>`<option value="${v}" ${v===c.layout?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`:''}${router?`<button class="button small" id="apiSettingsBtn" ${busy()?'disabled':''}>${state.api_key_saved?'✓ API bağlantısı':'API anahtarı ekle'}</button><button class="button small" id="refreshApiModels" ${busy()?'disabled':''}>Modelleri yenile</button>`:''}<p>${isLocal()?'İnternet ve model kullanmaz. Sınır, yön ve eşleşmeleri kontrol et.':router?'OpenRouter ücretli API kullanımı. Yalnız görsel + JSON destekli modeller. Seçenek bildirmeyen modellerde effort varsayılanda kalır.':'Görseller seçtiğin modele gönderilir. Model veya effort kendiliğinden değiştirilmez.'}</p>`;
 $('#modelState').textContent=isLocal()?'Yerel işlem · Çevrimdışı':(router?'OpenRouter · ':'')+selected.name+' · '+c[ekey];
}
$('#processingSettings').addEventListener('change',e=>act(async()=>{
 const c={...state.settings},router=c.backend==='openrouter',models=router?state.openrouter.models:state.models,mkey=router?'api_model':'model',ekey=router?'api_effort':'effort';
 if(e.target.id==='backendSelect')c.backend=e.target.value;
 if(e.target.id==='modelSelect'){c[mkey]=e.target.value;const m=models.find(m=>m.id===c[mkey]);if(m&&!m.efforts.includes(c[ekey]))c[ekey]=router?'default':m.efforts.includes('medium')?'medium':m.efforts[0];}
 if(e.target.id==='effortSelect')c[ekey]=e.target.value;
 if(e.target.id==='layoutSelect')c.layout=e.target.value;
 try{await api('/api/settings',c);state.settings=c;}finally{renderSettings();if(!dirty)render();}
}));
$('#processingSettings').addEventListener('click',e=>act(async()=>{
 if(e.target.id==='apiSettingsBtn'){$('#apiKey').value='';$('#apiStatus').textContent=state.api_key_saved?'Anahtar kayıtlı; güvenlik için tekrar gösterilmez.':'Henüz anahtar kaydedilmedi.';$('#apiDialog').showModal();}
 if(e.target.id==='refreshApiModels'){e.target.disabled=true;e.target.textContent='Yükleniyor…';try{state.openrouter=await api('/api/openrouter/models',{});toast(`${state.openrouter.models.length} uyumlu model bulundu.`);}finally{renderSettings();}}
}));
$('#closeApi').onclick=()=>{$('#apiKey').value='';$('#apiDialog').close();};
$('#apiDialog').addEventListener('close',()=>{$('#apiKey').value='';});
async function apiAction(fn){const buttons=$('#apiDialog').querySelectorAll('button');buttons.forEach(b=>b.disabled=true);try{$('#apiStatus').textContent=await fn();}catch(e){$('#apiStatus').textContent=e.message;}finally{$('#apiKey').value='';buttons.forEach(b=>b.disabled=false);renderSettings();}}
$('#saveApiKey').onclick=()=>apiAction(async()=>{await api('/api/openrouter/key',{key:$('#apiKey').value.trim()});state.api_key_saved=true;return 'Anahtar Anahtar Zinciri’ne kaydedildi. Bağlantıyı deneyebilirsin.';});
$('#testApiKey').onclick=()=>apiAction(async()=>{const r=await api('/api/openrouter/test',{});return r.message;});
$('#deleteApiKey').onclick=()=>apiAction(async()=>{await api('/api/openrouter/key',{delete:true});state.api_key_saved=false;return 'Bu uygulamanın kayıtlı anahtarı silindi.';});
function render(){
 renderSettings();
 const b=batch();if(!b){$('#app').innerHTML=`<div class="empty"><p class="eyebrow">FOTOĞRAFLAR VE ARKALARINDAKİ HİKÂYELER</p><h1>Bir taramada çok fotoğraf.<br>Arşivde her biri ayrı.</h1><p>Ön ve arka taramalarını bırak. Fotoğrafları ayıralım, eğik kenarları düzeltelim ve yazılarını yanlarına koyalım.</p><button class="button primary" data-action="new">İlk işi oluştur ＋</button><div class="steps"><span><b>01</b>Taramaları ekle</span><span><b>02</b>Eşleşmeleri gözden geçir</span><span><b>03</b>JPEG olarak kaydet</span></div></div>`;$('#exportTop').disabled=true;return;}
 if(!b.scans.some(s=>s.id===sid))sid=b.scans[0]?.id;
 if(!b.pairs.some(p=>p.id===pid))pid=b.pairs[0]?.id;
 if(!b.regions.some(r=>r.id===rid))rid=b.regions.find(r=>r.scan_id===sid)?.id;
 $('#exportTop').disabled=!approved().length||busy()||dirty;
 $('#app').innerHTML=`<div class="workspace"><aside class="sidebar"><p class="eyebrow">ÇALIŞMA MASASI</p><select class="batch-select" id="batchSelect" aria-label="Tarama işi">${state.batches.map(x=>`<option value="${x.id}" ${x.id===bid?'selected':''}>${esc(x.name)}</option>`).join('')}</select><div class="section-heading"><h3>Taramalar</h3><span class="counter">${b.scans.length}</span></div><div class="drop-small" data-action="upload">＋ Taramaları ekle<br><small>veya buraya sürükle</small></div><div class="scan-list">${b.scans.map(s=>`<div class="scan-item ${s.id===sid?'active':''}" data-scan="${s.id}" tabindex="0" role="button" aria-label="${esc(s.name)}"><img src="${scanURL(s)}" alt="" loading="lazy"><div><div class="name">${esc(s.name)}</div><div class="meta">${s.page>1?'Sayfa '+s.page+' · ':''}${s.width} × ${s.height}</div><select data-role-hint="${s.id}" aria-label="${esc(s.name)} yüz ipucu">${[['auto','Ön / arka otomatik'],['front','Ön yüz taraması'],['back','Arka yüz taraması']].map(([v,t])=>`<option value="${v}" ${s.role_hint===v?'selected':''}>${t}</option>`).join('')}</select></div></div>`).join('')}</div><div class="sidebar-foot">Orijinal taramalar korunur.<br>Her kayıtta yeni çıktı klasörü oluşturulur.</div></aside><section class="main-panel"><div class="page-heading"><div><h1>${esc(b.name)}</h1><p>${b.pairs.length?`${b.pairs.length} fotoğraf · ${approved().length} onaylı · ${b.pairs.length-approved().length} inceleme bekliyor`:'Önleri ve arkaları birlikte ekleyebilirsin.'}</p></div>${b.undo_available?'<button class="button small" data-action="undo" title="Son değişikliği geri al">↶ Geri al</button>':''}</div>${b.scans.length?`<div class="tabs"><button data-tab="scans" class="${tab==='scans'?'active':''}">Taramayı düzenle</button><button data-tab="results" class="${tab==='results'?'active':''}">Fotoğraflar <span class="counter">${b.pairs.length}</span></button></div>${tab==='results'?resultsView():scanView()}`:emptyView()}</section><aside class="inspector">${inspector()}</aside></div>`;
 bindCanvas();
}
function emptyView(){return `<div class="empty"><p class="eyebrow">ÖNCE TARAMALAR</p><h1>Birlikte taradın.<br>Ayrı ayrı saklayalım.</h1><p>Bir veya birden fazla taramayı ekle. Arka yazıları ayrı dosyalardaysa onları da aynı işe bırak.</p><div class="big-drop" data-action="upload" tabindex="0" role="button"><span class="plus">＋</span><strong>Taramaları buraya bırak</strong><small>JPEG, PNG, PDF, TIFF veya HEIC · Çoklu seçim</small></div><div class="steps"><span><b>01</b>Ekle</span><span><b>02</b>Eşleştir</span><span><b>03</b>Kaydet</span></div></div>`;}
function resultsView(){const b=batch();if(!b.pairs.length)return '<div class="quiet-text">Henüz ayrılmış fotoğraf yok. Sağdaki düğmeyle İşlemi başlat.</div>';return `<div class="result-grid">${b.pairs.map((p,i)=>`<article class="photo-card ${p.id===pid?'active':''}" data-pair="${esc(p.id)}" tabindex="0" role="button"><div class="photo"><img src="${preview(p)}" alt="${esc(p.name)}" loading="lazy"></div><div class="info"><span class="number">${String(i+1).padStart(3,'0')}</span><div class="title">${esc(p.name)}</div><span class="chip ${p.needs_review?'review':''}">${p.needs_review?'● Kontrol et':'✓ Onaylı'}</span> <span class="chip">${p.back_id?'Ön + arka':p.back_status==='blank'?'Arkası boş':'Tek yüz'}</span></div></article>`).join('')}</div>${b.notes?`<details class="processing-notes"><summary>İşlem notları</summary><p>${esc(b.notes)}</p></details>`:''}<p class="archive-note">Dikey fotoğraflarda ön solda, arka sağda; yataylarda ön üstte, arka altta. Yazılar fotoğrafın yönünü izler.</p>`;}
function scanView(){const b=batch(),s=b.scans.find(x=>x.id===sid);if(!s)return '';const regs=b.regions.filter(r=>r.scan_id===sid);return `<div class="scan-toolbar"><button class="button small" data-action="add-region" ${busy()?'disabled':''}>＋ Fotoğraf sınırı ekle</button><button class="button small" data-action="zoom">${scanView.zoom?'Sığdır':'Büyüt'}</button><span class="help">Köşeleri sürükleyerek düzelt</span></div><div class="scan-scroll"><div class="scan-stage" style="${scanView.zoom?'width:160%;max-width:none;':''}"><img id="sourceImage" src="${scanURL(s)}" alt="Orijinal tarama"><svg id="cornerCanvas" viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-label="Fotoğraf sınırları">${polygons(regs)}</svg></div></div><div class="legend"><span><i></i>Bulunan fotoğraflar</span><span><i class="selected"></i>Seçili sınır</span></div>${dirty?'<div class="dirty">● Kaydedilmemiş köşe değişikliği var</div>':''}`;}
function polygons(regs){return regs.map((r,i)=>`<polygon data-region="${esc(r.id)}" class="${r.id===rid?'active':''}" points="${r.corners.map(([x,y])=>`${x*1000},${y*1000}`).join(' ')}"></polygon><text x="${r.corners[0][0]*1000+12}" y="${r.corners[0][1]*1000+34}">${i+1}</text>${r.id===rid?r.corners.map(([x,y],j)=>`<circle data-corner="${j}" cx="${x*1000}" cy="${y*1000}" r="10"></circle>`).join(''):''}`).join('');}
function inspector(){const b=batch();if(!b.scans.length)return `<div class="welcome-aside"><div class="mini-card"></div><h2>Fotoğraf bir bütün.</h2><p class="muted">Önündeki görüntüyle, arkasındaki el yazısıyla.</p><p class="help">Uygulama eşleşmeyi önerir. Son söz sende: sınırı, yönü ve eşleşmeyi değiştirebilirsin.</p></div>`;
 const controls=isLocal()?`<hr><p class="eyebrow">YEREL İŞLEME</p><p class="help">Kâğıt sınırları bulunur, a/b çiftleri konum ve boyuta göre eşleştirilir. Dikey/yatay yönü sen kontrol edersin. Boş arka adayları eklenmez; bütün sonuçlar onay bekler.</p><p class="help">Fotoğraflar birbirine değiyorsa üstten 2 × 2 gibi yerleşim seç. Serbest metinle düzeltme ve konuya göre adlandırma için yapay zekâ moduna geçebilirsin.</p><button class="button primary full" data-action="analyze" ${busy()||dirty?'disabled':''}>${busy()?'İşleniyor…':b.pairs.length?'Yerel olarak yeniden işle':'Yerel olarak ayır ve eşleştir'}</button>`:`<hr><p class="eyebrow">YAPAY ZEKÂYA NOT</p><textarea id="instruction" placeholder="Örn. Sağ üsttekinin arkası boş.">${esc(drafts[bid]??b.instruction)}</textarea><p class="help">Görseller seçtiğin modele gönderilir. Kırpma ve birleştirme bu Mac'te yapılır.</p><button class="button primary full" data-action="${b.pairs.length&&!pendingScans()?'revise':'analyze'}" ${busy()||dirty?'disabled':''}>${busy()?'İşleniyor…':b.pairs.length&&!pendingScans()?'Notuma göre düzelt':'Yapay zekâ ile ayır ve eşleştir'}</button>${b.pairs.length?`<button class="button small full" data-action="analyze" ${busy()||dirty?'disabled':''}>Tüm taramaları yeniden analiz et</button>`:''}`;

 if(tab==='results'&&pair()){
   const p=pair(),r=b.regions.find(r=>r.id===p.front_id);return `<p class="eyebrow">FOTOĞRAF ${String(b.pairs.indexOf(p)+1).padStart(3,'0')}</p><h2>Eşleşmeyi düzenle</h2><a class="button small full" href="${preview(p)}" target="_blank" rel="noopener">Önizlemeyi büyük aç ↗</a><span class="chip ${p.needs_review?'review':''}">${p.needs_review?'Kontrol bekliyor':'Onaylandı'}</span><label>Dosya adı<input id="pairName" value="${esc(p.name)}" maxlength="100"></label><label>Arka yüz<select id="pairBack"><option value="">Arka yüz seçilmedi</option>${b.regions.filter(r=>r.role==='back').map(r=>`<option value="${esc(r.id)}" ${r.id===p.back_id?'selected':''}>${esc(r.label)} · ${esc(r.scan_id)}</option>`).join('')}</select></label><label>Arka yüz durumu<select id="backStatus">${[['matched','Ön + arka eşleşti'],['blank','Arkası boş'],['not_provided','Arka yok — tek kaydet'],['uncertain','Eşleşme belirsiz']].map(([v,t])=>`<option value="${v}" ${p.back_status===v?'selected':''}>${t}</option>`).join('')}</select></label><label>Fotoğraf yönü</label><div class="rotation"><button class="button small" data-action="rotate-front">↻ 90° çevir</button><span>${r.rotation_clockwise}°</span></div>${p.back_id?`<label>Arka yüz yönü</label><div class="rotation"><button class="button small" data-action="rotate-back">↻ 180° çevir</button><span>${p.back_rotation_clockwise}°</span></div>`:''}<div class="note-box">${esc(p.matching_notes)}</div><div class="save-row"><button class="button" data-action="save-pair" ${busy()?'disabled':''}>Kaydet</button><button class="button primary" data-action="approve-pair" ${busy()?'disabled':''}>✓ Onayla</button></div><button class="button small full" data-action="edit-front">Fotoğrafın köşelerini düzelt</button>${p.back_id?'<button class="button small full" data-action="edit-back">Arkanın köşelerini düzelt</button>':''}${controls}`;
 }
 const r=region(),regs=b.regions.filter(r=>r.scan_id===sid);
 return `<p class="eyebrow">TARAMA SINIRLARI</p><h2>${regs.length?regs.length+' yüz bulundu':'Fotoğrafları ayıralım'}</h2>${regs.length?`<select id="regionSelect" class="region-select" aria-label="Düzenlenecek bölge">${regs.map((x,i)=>`<option value="${esc(x.id)}" ${x.id===rid?'selected':''}>${i+1}. ${esc(x.label)}</option>`).join('')}</select>`:''}${r&&r.scan_id===sid?`<label>Yüz türü<select id="regionRole">${[['front','Fotoğraf önü'],['back','Yazılı arka'],['blank','Boş arka']].map(([v,t])=>`<option value="${v}" ${r.role===v?'selected':''}>${t}</option>`).join('')}</select></label><label>Yön</label><div class="rotation"><button class="button small" data-action="rotate-region">↻ 90° çevir</button><span>${r.rotation_clockwise}°</span></div><p class="help">Dört köşeyi fotoğrafın gerçek kenarlarına getir. Eğiklik kayıtta otomatik düzeltilir.</p><button class="button primary full" data-action="save-corners" ${busy()?'disabled':''}>Köşeleri ve yönü kaydet</button><button class="button small danger full" data-action="remove-region" ${busy()?'disabled':''}>Bu sınırı kaldır</button>`:'<p class="help">Seçili yöntem fiziksel fotoğrafların sınırlarını önerir. Sonrasında köşeleri elle düzeltebilirsin.</p>'}${controls}`;
}
function bindCanvas(){const svg=$('#cornerCanvas');if(!svg)return;svg.addEventListener('pointerdown',e=>{if(busy())return;const c=e.target.closest('[data-corner]');if(c){drag=Number(c.dataset.corner);svg.setPointerCapture(e.pointerId);e.preventDefault();}else if(e.target.dataset.region){rid=e.target.dataset.region;render();}});svg.addEventListener('pointermove',e=>{if(drag===null)return;const rect=svg.getBoundingClientRect();region().corners[drag]=[Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width)),Math.max(0,Math.min(1,(e.clientY-rect.top)/rect.height))];dirty=true;svg.innerHTML=polygons(batch().regions.filter(r=>r.scan_id===sid));});const end=()=>{if(drag!==null){drag=null;render();}};svg.addEventListener('pointerup',end);svg.addEventListener('pointercancel',end);}
async function savePlan(){dirty=true;const b=batch();await api(`/api/batches/${bid}/plan`,{revision:b.revision,regions:b.regions,pairs:b.pairs,notes:b.notes});dirty=false;await refresh();}
async function leaveDirty(){if(!dirty)return true;if(confirm('Kaydedilmemiş değişiklikleri bırakmak istiyor musun?')){dirty=false;await refresh(false);return true;}return false;}
function readPair(){const p=pair();p.name=$('#pairName').value.trim()||'fotograf';p.back_id=$('#pairBack').value||null;p.back_status=$('#backStatus').value;if(['blank','not_provided'].includes(p.back_status))p.back_id=null;else if(!p.back_id&&p.back_status==='matched')p.back_status='uncertain';}
async function action(name){
 if(busy()&&!['new','upload','zoom','edit-front','edit-back'].includes(name)){toast('İşlem sürerken düzenleme yapılamaz.');return;}
 if(name==='new'){$('#newDialog').showModal();$('#batchName').focus();return;}
 if(name==='upload'){if(!busy()&&!uploading)$('#fileInput').click();else toast('Devam eden işlemin bitmesini bekle.');return;}
 if(name==='zoom'){scanView.zoom=!scanView.zoom;render();return;}
 if(name==='undo'){if(!await leaveDirty())return;await api(`/api/batches/${bid}/undo`,{});await refresh();toast('Son değişiklik geri alındı.');return;}
 if(name==='analyze'||name==='revise'){
   if(dirty)throw Error('Önce düzenlemelerini kaydet veya geri al.');
   const instruction=$('#instruction')?.value||'';
   if(name==='analyze'&&batch().pairs.length&&!confirm('Mevcut plan yeniden analiz edilsin mi? Önceki plan Geri al ile korunacak.'))return;
   await api(`/api/batches/${bid}/analyze`,{instruction,mode:name});await refresh();return;
 }
 if(name==='add-region'){
   const id=sid+'-'+Date.now().toString(36);batch().regions.push({id,scan_id:sid,role:'front',label:'Yeni fotoğraf',corners:[[.15,.15],[.85,.15],[.85,.85],[.15,.85]],rotation_clockwise:0,confidence:1});
   batch().pairs.push({id:'p-'+id,front_id:id,back_id:null,name:'yeni-fotograf',back_rotation_clockwise:0,back_status:'not_provided',confidence:1,needs_review:true,matching_notes:'Elle eklendi.'});rid=id;dirty=true;render();return;
 }
 if(name==='rotate-region'){region().rotation_clockwise=(region().rotation_clockwise+90)%360;dirty=true;render();return;}
 if(name==='save-corners'){
   const r=region(),role=$('#regionRole').value;
   if(role!==r.role){r.role=role;if(role!=='front')batch().pairs=batch().pairs.filter(p=>p.front_id!==r.id);else batch().pairs.push({id:'p-'+r.id,front_id:r.id,back_id:null,name:r.label,back_rotation_clockwise:0,back_status:'not_provided',confidence:1,needs_review:true,matching_notes:'Yüz türü elle değiştirildi.'});for(const p of batch().pairs)if(p.back_id===r.id&&role!=='back'){p.back_id=null;p.back_status='uncertain';p.needs_review=true;}}
   for(const p of batch().pairs)if(p.front_id===r.id||p.back_id===r.id)p.needs_review=true;
   await savePlan();toast('Köşeler kaydedildi. Sonuçlar yeniden hazırlanıyor.');return;
 }
 if(name==='remove-region'){const r=region();batch().regions=batch().regions.filter(x=>x.id!==r.id);batch().pairs=batch().pairs.filter(p=>p.front_id!==r.id);for(const p of batch().pairs)if(p.back_id===r.id){p.back_id=null;p.back_status='uncertain';p.needs_review=true;}await savePlan();return;}
 if(['save-pair','approve-pair','rotate-front','rotate-back'].includes(name)){
   readPair();const p=pair();
   if(name==='rotate-front'){const r=batch().regions.find(r=>r.id===p.front_id);r.rotation_clockwise=(r.rotation_clockwise+90)%360;p.needs_review=true;}
   else if(name==='rotate-back'){p.back_rotation_clockwise=(p.back_rotation_clockwise+180)%360;p.needs_review=true;}
   else p.needs_review=name!=='approve-pair';
   if(name==='approve-pair'&&p.back_status==='uncertain')throw Error('Önce arka yüzü seç veya arka yüz durumunu belirt.');
   await savePlan();toast(name==='approve-pair'?'Eşleşme onaylandı.':'Değişiklik kaydedildi.');return;
 }
 if(name==='edit-front'||name==='edit-back'){rid=pair()[name==='edit-front'?'front_id':'back_id'];sid=region().scan_id;tab='scans';render();}
}
$('#app').addEventListener('click',e=>act(async()=>{const a=e.target.closest('[data-action]');if(a){act(()=>action(a.dataset.action));return;}if(e.target.tagName==='SELECT')return;const s=e.target.closest('[data-scan]');if(s){if(!await leaveDirty())return;sid=s.dataset.scan;rid=batch().regions.find(r=>r.scan_id===sid)?.id;tab='scans';render();return;}const p=e.target.closest('[data-pair]');if(p){if(!await leaveDirty())return;pid=p.dataset.pair;render();return;}const t=e.target.closest('[data-tab]');if(t){if(!await leaveDirty())return;tab=t.dataset.tab;await refresh();}}));
$('#app').addEventListener('input',e=>{if(e.target.id==='instruction'){drafts[bid]=e.target.value;}else if(['pairName','pairBack','backStatus','regionRole'].includes(e.target.id)){dirty=true;$('#exportTop').disabled=true;}});
$('#app').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[role="button"]')){e.preventDefault();e.target.click();}});
$('#app').addEventListener('change',e=>act(async()=>{if(e.target.id==='batchSelect'){if(!await leaveDirty())return;bid=e.target.value;sid=pid=rid=null;await refresh();}else if(e.target.dataset.roleHint){const selectedValue=e.target.value,scanId=e.target.dataset.roleHint;if(!await leaveDirty())return;await api(`/api/batches/${bid}/scan/${scanId}`,{role_hint:selectedValue,revision:batch().revision});await refresh();}else if(e.target.id==='regionSelect'){rid=e.target.value;render();}else if(e.target.id==='pairBack'){if(e.target.value)$('#backStatus').value='matched';else $('#backStatus').value='uncertain';}}));
$('#newBatch').onclick=()=>action('new');$('#closeNew').onclick=()=>$('#newDialog').close();
$('#newForm').onsubmit=e=>{e.preventDefault();act(async()=>{if(!await leaveDirty())return;const b=await api('/api/batches',{name:$('#batchName').value});bid=b.id;sid=pid=rid=null;tab='scans';$('#newDialog').close();$('#batchName').value='';await refresh();});};
async function upload(files){if(!await leaveDirty())return;if(busy())throw Error('İşlem sürerken tarama eklenemez.');if(!batch()){const b=await api('/api/batches',{name:'Fotoğraf arşivi '+new Date().toLocaleDateString('tr-TR')});bid=b.id;await refresh(false);}uploading=true;toast('Taramalar içe aktarılıyor…');const fd=new FormData();[...files].forEach(f=>fd.append('files',f));try{const r=await api(`/api/batches/${bid}/upload`,fd);await refresh();toast(`${r.added} tarama eklendi.${r.errors.length?' '+r.errors.join(' · '):''}`);}finally{uploading=false;}}
$('#fileInput').onchange=e=>act(async()=>{await upload(e.target.files);e.target.value='';});
document.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files')){e.preventDefault();$('.drop-small,.big-drop')?.classList.add('dragover');}});document.addEventListener('dragleave',()=>$('.dragover')?.classList.remove('dragover'));document.addEventListener('drop',e=>{if(e.dataTransfer.files.length){e.preventDefault();$('.dragover')?.classList.remove('dragover');act(()=>upload(e.dataTransfer.files));}});
$('#cancelJob').onclick=()=>act(async()=>{await api('/api/cancel',{});toast('İptal ediliyor…');});
$('#exportTop').onclick=()=>{const b=batch();$('#exportDir').value=state.export_default;$('#exportCount').textContent=`${approved().length} onaylı fotoğraf kaydedilecek. ${b.pairs.length-approved().length} inceleme bekleyen fotoğraf bu kayda dahil edilmez.`;$('#exportResult').innerHTML='';$('#doExport').disabled=false;$('#doExport').textContent='Onaylı fotoğrafları kaydet';$('#exportDialog').showModal();};
$('#doExport').onclick=()=>act(async()=>{const btn=$('#doExport');btn.disabled=true;btn.textContent='Tam çözünürlükte kaydediliyor…';try{await refresh(false);const result=await api(`/api/batches/${bid}/export`,{revision:batch().revision,directory:$('#exportDir').value});$('#exportResult').innerHTML=`<div class="result-success"><strong>${result.files.length} JPEG kaydedildi.</strong><br>${esc(result.directory)}<br><button class="button small" id="revealExport">Finder'da göster</button> <a class="button small" href="/api/exports/${result.id}/zip">ZIP indir</a></div>`;$('#revealExport').onclick=()=>act(()=>api(`/api/exports/${result.id}/reveal`,{}));btn.textContent='Kaydedildi ✓';await refresh(false);}catch(e){$('#exportResult').innerHTML=`<p role="alert">${esc(e.message)}</p>`;btn.disabled=false;btn.textContent='Yeniden dene';throw e;}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
setInterval(async()=>{try{const next=await api('/api/state',undefined,'GET');const key=JSON.stringify(next.job);if(key!==lastJob){const was=state?.job.status;lastJob=key;if(!dirty){state=next;updateJob();if(was==='running'&&next.job.status!=='running'){if(next.job.status==='done')tab='results';render();}else if(next.job.status==='running'){updateJob();}}}}catch{}},2000);
$('#languageSelect').value=window.APP_LANGUAGE;
$('#languageSelect').onchange=e=>act(async()=>{const language=e.target.value;if(!await leaveDirty()){e.target.value=window.APP_LANGUAGE;return;}document.cookie='photo-desk-language='+language+'; Path=/; SameSite=Strict; Max-Age=31536000';location.reload();});
act(()=>refresh());
